#[chapa::bitfield(u32, width = 32, order = msb0)]
#[derive(Clone, Copy, Default)]
pub struct Srr0 {
    #[bits(0..=29)]
    pub value: u32, // low 2 bits are always 0
}

#[derive(Default)]
pub struct Spr {
    pub xer: u32,
    pub lr: u32,
    pub ctr: u32,
    pub dsisr: u32,
    pub dar: u32,
    pub dec: u32,
    pub sdr1: u32,
    pub srr0: Srr0,
    pub srr1: u32,
    pub sprg0: u32,
    pub sprg1: u32,
    pub sprg2: u32,
    pub sprg3: u32,
    pub ear: u32,
    pub pvr: u32,
    pub ibat0u: u32,
    pub ibat0l: u32,
    pub ibat1u: u32,
    pub ibat1l: u32,
    pub ibat2u: u32,
    pub ibat2l: u32,
    pub ibat3u: u32,
    pub ibat3l: u32,
    pub dbat0u: u32,
    pub dbat0l: u32,
    pub dbat1u: u32,
    pub dbat1l: u32,
    pub dbat2u: u32,
    pub dbat2l: u32,
    pub dbat3u: u32,
    pub dbat3l: u32,
    pub dabr: u32,
}

impl Spr {
    pub fn read(&self, spr_num: u32) -> u32 {
        match spr_num {
            1 => self.xer,
            8 => self.lr,
            9 => self.ctr,
            18 => self.dsisr,
            19 => self.dar,
            22 => self.dec,
            25 => self.sdr1,
            26 => self.srr0.value(),
            27 => self.srr1,
            272 => self.sprg0,
            273 => self.sprg1,
            274 => self.sprg2,
            275 => self.sprg3,
            282 => self.ear,
            287 => self.pvr,
            528 => self.ibat0u,
            529 => self.ibat0l,
            530 => self.ibat1u,
            531 => self.ibat1l,
            532 => self.ibat2u,
            533 => self.ibat2l,
            534 => self.ibat3u,
            535 => self.ibat3l,
            536 => self.dbat0u,
            537 => self.dbat0l,
            538 => self.dbat1u,
            539 => self.dbat1l,
            540 => self.dbat2u,
            541 => self.dbat2l,
            542 => self.dbat3u,
            543 => self.dbat3l,
            1013 => self.dabr,
            _ => panic!("unknown SPR {spr_num}"),
        }
    }

    pub fn write(&mut self, spr_num: u32, value: u32) {
        match spr_num {
            1 => self.xer = value,
            8 => self.lr = value,
            9 => self.ctr = value,
            18 => self.dsisr = value,
            19 => self.dar = value,
            22 => self.dec = value,
            25 => self.sdr1 = value,
            26 => self.srr0 = Srr0::from(value),
            27 => self.srr1 = value,
            272 => self.sprg0 = value,
            273 => self.sprg1 = value,
            274 => self.sprg2 = value,
            275 => self.sprg3 = value,
            282 => self.ear = value,
            287 => self.pvr = value,
            528 => self.ibat0u = value,
            529 => self.ibat0l = value,
            530 => self.ibat1u = value,
            531 => self.ibat1l = value,
            532 => self.ibat2u = value,
            533 => self.ibat2l = value,
            534 => self.ibat3u = value,
            535 => self.ibat3l = value,
            536 => self.dbat0u = value,
            537 => self.dbat0l = value,
            538 => self.dbat1u = value,
            539 => self.dbat1l = value,
            540 => self.dbat2u = value,
            541 => self.dbat2l = value,
            542 => self.dbat3u = value,
            543 => self.dbat3l = value,
            1013 => self.dabr = value,
            _ => panic!("unknown SPR {spr_num}"),
        }
    }
}
