[[gen]]
input = "../../submodules/chipi-spec/gamecube/gekko.chipi"
lang = "rust"
output = "$OUT_DIR/gekko.rs"

[gen.type_map]
gpr = "crate::cpu::Gpr"
fpr = "crate::cpu::Fpr"

[[gen]]
input = "../../submodules/chipi-spec/gamecube/dsp.chipi"
lang = "rust"
output = "$OUT_DIR/dsp.rs"
